apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: redis-rs
  labels:
    app: redis
    env: master
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
      env: master
  template:
    metadata:
      labels:
        app: redis
        env: master
        creator: gerry
    spec:
      containers:
        - name: redis
          image: redis:latest
          imagePullPolicy: IfNotPresent
          command:
            - "redis-server"
          args:
              - /usr/local/etc/redis/redis_6379.conf
          volumeMounts:
            - mountPath: /data  #容器的地址
              name: redis-data #对应上面卷的名称
            - mountPath: /usr/local/etc/redis/redis_6379.conf #容器的地址
                name: redis-cm
                subPath: redis_6379.conf
          ports:
            - name: http
              containerPort: 6379
      volumes:
        - name: redis-data
          hostPath:
            path: /data/redis/data
            type: DirectoryOrCreate
        - name: redis-data
            persistentVolumeClaim:
              claimName: redis-pvc  # 这里填写pvc的名称
        - name: redis-cm
          configMap:
            name: redis-cm
            items:
            - key: redis_6379.conf
              path: redis_6379.conf