apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: blogapi-rs
  labels:
    app: blogapi
    env: master
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blogapi
      env: master
  template:
    metadata:
      labels:
        app: blogapi
        env: master
        creator: gerry
    spec:
      containers:
        - name: blogapi
          image: xiaoyaoguai/blogapi:v1
          imagePullPolicy: IfNotPresent
          #command: ["/bin/bash","-ce","tail -f /dev/null"]
          ports:
            - name: http
              containerPort: 8000