<?php
/**
 * Class AppUser
 * @package app\common\logic\user
 * author:lzcong
 * time:22:13
 * comment:说明
 * package:包命，命名空间
 * todo todolis:类中还需要完善的功能列表
 */

namespace app\common\logic\user;

use app\common\logic\Base;

class AppUser extends Base implements AbsUser
{
    public function setmodel($model)
    {
        parent::setmodel($model); // TODO: Change the autogenerated stub
    }

    public function login($param)
    {
        $account = $param['account'];
        $pwd = md5($param['pwd']);
        $AppUserInfo = $this->model->getAccountInfo($account);
        if(!$AppUserInfo) E('账号不存在');
        switch ($AppUserInfo['status']){
            case 1:
                E('账号注销中');
            case 2:
                E('账号已拉黑');
        }
        if($pwd != $AppUserInfo->pwd) E('密码错误');
        $AppUserInfo->last_time = time();
        $AppUserInfo->last_ip = request()->ip();
        $AppUserInfo->login_count++;
        $AppUserInfo->save();
        // TODO: Implement login() method.
    }

    public function getInfo($uid)
    {
        // TODO: Implement getInfo() method.
    }

    /**
     * 微信登陆 扫码
     * @return void
     */
    public function wxLogin($accToken ,$param)
    {

    }

}